# Generated by Django 4.2.1 on 2023-05-21 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from ..data_populators import populate_poblaciones, populate_tipo_establecimiento


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.today, editable=False)),
                ('actualizado_por', models.CharField(editable=False, max_length=150, null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='InternalData',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetadatosEstablecimiento',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_api.establecimiento')),
                ('coordenadas_cansultadas_en', models.DateTimeField(blank=True, null=True)),
                ('estado_operacional_consultado_en', models.DateTimeField(blank=True, null=True)),
                ('resultado_consulta_google', models.CharField(blank=True, max_length=20, null=True)),
                ('id_sitio_google', models.TextField(blank=True, null=True)),
                ('nombre_segun_google_candidato1', models.TextField(blank=True, null=True)),
                ('estado_segun_google_candidato1', models.TextField(blank=True, null=True)),
                ('nombre_segun_google_candidato2', models.TextField(blank=True, null=True)),
                ('estado_segun_google_candidato2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_api.poblacion'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_api.tipoestablecimiento'),
        ),
        migrations.RunPython(populate_tipo_establecimiento),
        migrations.RunPython(populate_poblaciones),
    ]
