# Generated by Django 4.2.1 on 2023-05-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
