# Generated by Django 4.2.1 on 2023-05-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_establecimiento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
