# Generated by Django 4.2.1 on 2023-05-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_establecimiento_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='poblacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
