# Generated by Django 4.2.1 on 2023-05-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_alter_establecimiento_poblacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
