# Generated by Django 4.2.1 on 2023-05-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_alter_establecimiento_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
