# Generated by Django 4.2.1 on 2023-05-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_alter_establecimiento_latitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatosestablecimiento',
            old_name='coordenadas_cansultadas_en',
            new_name='coordenadas_consultadas_en',
        ),
    ]
