# Generated by Django 4.2.1 on 2023-05-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_rename_coordenadas_cansultadas_en_metadatosestablecimiento_coordenadas_consultadas_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatosestablecimiento',
            old_name='coordenadas_consultadas_en',
            new_name='nominatim_checked',
        ),
    ]
