# Generated by Django 4.2.1 on 2023-05-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_rename_coordenadas_consultadas_en_metadatosestablecimiento_nominatim_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatosestablecimiento',
            old_name='estado_operacional_consultado_en',
            new_name='google_checked',
        ),
    ]
