# Generated by Django 4.2.1 on 2023-05-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_rename_id_sitio_google_metadatosestablecimiento_nominatim_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='telefonos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='web',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
