# Generated by Django 4.2.1 on 2023-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0013_establecimiento_telefonos_establecimiento_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
