# Generated by Django 4.2.1 on 2023-05-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0016_rename_descripcion_establecimiento_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
